import type { Metadata } from 'next';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/utils/theme';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <ThemeProvider theme={theme}>
          {/* <Navbar /> */}
          {children}
          {/* <Footer /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
